name: Publish documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '^3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc
          pip install .
      - name: Build documentation
        run: |
          pdoc src/ainfo -o site
          touch site/.nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/ainfo
